name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: {}

permissions:
  actions: read
  contents: read

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'yarn'


      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Move files
        run: 
          - mv dist/apps/scoreboard/index.html dist/apps/scoreboard/view.html
          - mv dist/apps/scoreboard-setup/index.html dist/apps/scoreboard/index.html
          - mv dist/apps/scoreboard-setup/assets/* dist/apps/scoreboard/assets

      - name: Upload dist/apps/scoreboard
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/apps/scoreboard


  deploy:
    name: Deploy

    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy scoreboard
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
